services:
  posgres:
    image: postgres:latest
    ports:
      - "5420:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts/entrypointtwo.sh:/docker-entrypoint-initdb.d/entrypointtwo.sh
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/entrypointtwo.sh"]
    command: ["postgres"]
    networks:
      - zapzapClone
    restart: always
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "6969:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - zapzapClone
    restart: always
    command:
      - "start-dev"
networks:
  zapzapClone:
    driver: bridge
volumes:
  postgres:
    driver: local