/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Message } from '../models/message';
import { User } from '../models/user';
export interface Chat {
  createdAt?: string;
  id?: string;
  messages?: Array<Message>;
  receiver?: User;
  sender?: User;
  updatedAt?: string;
}
