/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Chat } from '../models/chat';
export interface User {
  chatsAsReceiver?: Array<Chat>;
  chatsAsSender?: Array<Chat>;
  createdAt?: string;
  email?: string;
  firstName?: string;
  id?: string;
  lastName?: string;
  lastSeenAt?: string;
  online?: boolean;
  updatedAt?: string;
}
