/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface PatchMethodName$Params {
  'chat-id': string;
  'message-id': string;
  status: 'SENT' | 'RECEIVED' | 'SEEN';
}

export function patchMethodName(http: HttpClient, rootUrl: string, params: PatchMethodName$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, patchMethodName.PATH, 'patch');
  if (params) {
    rb.query('chat-id', params['chat-id'], {});
    rb.query('message-id', params['message-id'], {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

patchMethodName.PATH = '/message';
